#+TITLE: Which shell to use
#+DATE: 2014-10-30
#+SETUPFILE: ~/Documents/coding/blog/octopress/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: 
#+JEKYLL_PUBLISHED: true

* with emacs
** eshell
- autocomplete work
- sshfs
- kill & yank works
- *Eshell does not support input redirection*
- http://askubuntu.com/questions/229447/how-do-i-diff-the-output-of-two-commands
- ssh hangs on!!!
- [[http://www.gnu.org/software/emacs/manual/html_mono/eshell.html#Introduction][gnu manual]] -> 
{% codeblock %}
Eshell is not a replacement for system shells such as bash or zsh. 
Use Eshell when you want to move text between Emacs and external processes; 
if you only want to pipe output from one external process to another (and then another, and so on), use a system shell, 
because Emacs's IO system is buffer oriented, not stream oriented, and is very inefficient at such tasks. 
If you want to write shell scripts in Eshell, don't; either write an elisp library or use a system shell. 
{% endcodeblock %}

** others
- M-x shell
 - autocomplete doesn't work (when =ssh= ing)
 - kill & yank works

- M-x term (ansi-term)
 - autocomplete works
 - +kill & yank doesn't work+ Actually it works, [[http://stackoverflow.com/questions/2886184/copy-paste-in-emacs-ansi-term-shell][here]].

* in terminal, 
** zsh or fish?

* COMMENT
https://snarfed.org/why_i_run_shells_inside_emacs
http://stackoverflow.com/questions/4683256/tab-completion-in-emacs-shell-mode-ssh-sessions

shell-resync-dirs


{{{more}}}
