#+TITLE: Set up my blog
#+DATE: 2014-10-26
#+SETUPFILE: ~/Documents/coding/blog/octopress/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: [emacs, blog]
#+JEKYLL_PUBLISHED: true

I previously used my secondary Facebook account as a blog, but soon I felt need for another platform.
I wanted to open my posting with my editor (emacs, org-mode) and update with my VCS (git).
Simple static web site looked fine for me, as [[https://github.com/discourse/discourse][Discourse]] or [[https://disqus.com/][Disqus]] seems to provide satisfiable commenting feature.
I've looked through some examples below.
- [[http://orgmode.org/worg/org-web.html][org web sites]]
- [[http://orgmode.org/worg/org-blog-wiki.html][org blogging tools]]
- [[https://github.com/joshuaeckroth/cse3521-website][cse3521-website]]
As a total newbie on web front-end programming, org-mode, elisp, and blogging, I
- myself doesn't know exactly which feature I want.
- am hard to deal with problems when I stuck.
Therefore, large and active community was especially important factor for me.


* Blogging tool
** [[http://renard.github.io/o-blog-v2/][o-blog]]
stuck with this issue : https://github.com/renard/o-blog/issues/116#issuecomment-59183307
** [[http://octopress.org/][Octopress]] with [[https://github.com/yoshinari-nomura/org-octopress][org-octopress]]
I also noticed [[http://blog.paphus.com/blog/2012/08/01/introducing-octopress-blogging-for-org-mode/][this post]] and tried it. 
I'm not sure of pros and cons of each, but I followed upper link because
- It looks simpler.
- It is in Elpa package list, while the other is not.
- More recent, more users (concerning github stars)
- [[http://www.railsonmaui.com/blog/2014/03/05/octopress-setup-with-github-and-org-mode-v2/][newer post of this blog]] suggests to use it, while the [[http://www.railsonmaui.com/blog/2013/04/27/octopress-setup-with-github-and-org-mode/][older post of this blog]] suggests to use the other.

* Deploying tool
** Heroku
I followed [[http://octopress.org/docs/deploying/heroku/][instructions]] but somehow it didn't work for me.
** Github page
It works.

* Table Styling
| a | b | c |
|---+---+---|
| 2 | 4 | 6 |
| 1 | 3 | 5 |

| a | b | c |
|---+---+---|
| 2 | 4 | 6 |
| 1 | 3 | 5 |

Had trouble with table styling, it didn't have any border. 
I followed [[http://samwize.com/2012/09/24/octopress-table-stylesheet/][this]] to resolve. 
Anyway, this styling doesn't work when table is placed after title. (here, "Table Styling")
I'm total noob on front-end and I was only able to check with
Chrome developer tool - magnifier, that the table is "screen.css", not "data-table.css".


* _posts directory
Added .gitignore to ignore "source/_posts" directory.
I think this directory is managed in "org-octopress" only, and Html files there can be recoverd from .org files.
* org-octopress customization
https://github.com/sven--/org-octopress

* TODO smart-dash problem
https://github.com/yoshinari-nomura/org-octopress/issues/15
not resolved yet.
{% gist 7fc8aacfe0bb33577955 %}


* rake preview, eshell, text encoding
While executing "rake preview" in eshell,
there was some issue concerning text encoding.
Problem rose up when I was inserting gist. 
Below is example, first was OK and second made problem.

{% gist bcf4ecae74efa39d6605 %}
{% gist b3237d914680eafb3369 %}

I'm not sure but if I remember correctly, error message was something like below.
{% codeblock %}
Liquid Exception: invalid byte sequence in US-ASCII in _posts/2014-10-26-set-up-my-blog.html/#excerpt
jekyll 2.4.0 | Error:  invalid byte sequence in US-ASCII
{% endcodeblock %}

Can be easily resolved by below.

http://stackoverflow.com/questions/7165108/in-osx-lion-lang-is-not-set-to-utf8-how-fix
{% codeblock lang:sh %}
#!/bin/bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
{% endcodeblock %}

* rake preview, rvm
I had a problem which I cannot remember well.
After some troubleshooting, it turned out it was matter of gem versions.
I executed "gem list" in *M-x shell*, *M-x term*, *M-x eshell*, original terminal, respectively and it turned out to have 2 equiv. class.

shell = term 

original terminal = eshell

(login shell?)
I resolved it by
https://github.com/senny/rvm.el
With this and some rvm works, I have same gem lists for each shell.

* TODO comment?
** Discourse
http://www.railsonmaui.com/blog/2014/09/27/updating-to-jekyll-2-and-discourse-for-comments/
http://eviltrout.com/2014/01/22/embedding-discourse.html

Seems a bit difficult and I might need to pay. (digital ocean)

Looked for AWS but free plan only goes for 1 year.

Discourse site's github authorization doesn't work properly... sucks!

** Disqus
Compared to Discourse -> not open source, not full control?

Can't find "short url" after page goes... sucks!

http://hal.case.edu/~rrc/blog/2013/09/29/disqus-comments-not-visible/

*CANNOT SET WEBSITE URL (sven--.github.io) IN SETTINGS - GENERAL, IT REJECTS STRING WITH HYPEN.*

I don't see what the fuck is wrong. 
Error message is "Enter a valid URL." and that's all.
- abcd-.com -> Invalid
- -abcd.com -> Valid
- abc-d.com -> Valid
What should I do with my URL? (sven--.github.io)
give up


* TODO break line
org mode? html?
* TODO plain text more fancy formatting

* Theme
Using [[https://github.com/lucaslew/whitespace][whitespace]] theme.
Tried several other themes, but most of their styling was broken in some feature. (table, gist, math, etc) 

* COMMENT
{% gist 4321346 %}
{{{gist(4321346)}}}
{% gist 382223344569f523271b %}
{% gist 6507e8553f7cac286f9b %}



